version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t project1-container .
      - docker tag project1-container:068561046400.dkr.ecr.us-east-1.amazonaws.com/project1-ecr-repo
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - docker push 068561046400.dkr.ecr.us-east-1.amazonaws.com/project1-ecr-repo
      

