version: 0.2

phases:
  pre_build:
    commands:
       - echo Logging / auth in to Amazon ECR
       - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 068561046400.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Build started
      - echo Building the docker image
      - docker build -t project1-ecr-repo .
      - docker tag project1-ecr-repo:latest 068561046400.dkr.ecr.us-east-1.amazonaws.com/project1-ecr-repo:latest


  post_build:
    commands:
     - echo build completed
     - echo pushing in to docker ECR...
     - docker push 068561046400.dkr.ecr.us-east-1.amazonaws.com/project1-ecr-repo:latest
     - echo Writing image definition file..
     - printf '[{"name":"%s","imageUri":"%s"}]' "project1-ecs-cluster" "068561046400.dkr.ecr.us-east-1.amazonaws.com/project1-ecr-repo:latest" > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json
